### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by darekmer** [hahuweb/hahucms#1]
Hi, I'm using php 8.1 can't create a user, it spins around

**Comment by hahuweb** [comment]
Sorry darekmer about the mistake that you found. Please delete config.php
from hw-includes/config/ folder file or download again. I edited earlier.

**Comment by hahuweb** [comment]
Sorry darekmer about the mistake that you found. Please delete config.php
file from hw-includes/config/ folder or download again. I edited earlier.

**Comment by hahuweb** [comment]
Sorry darekmer about the mistake that you found. Please delete config.php file from hw-includes/config/ folder or download again. I edited earlier.

**Comment by darekmer** [comment]
Setting up the database is ok, then the installer goes to setting up an administrator account and here is the problem. i enter name, password and email, click create and preloaders spins and nothing happens.

**Comment by hahuweb** [comment]
Hello darekmer its working for me, please  delete config.php file,  create new database and try again. if it isn't working, on your browser, click view page source scroll down, find php error and tell me. Thank you.

**Comment by darekmer** [comment]
errors:
[Fri Jul 07 22:25:36.113061 2023] [php:warn] [pid 387153] [client fe80::2813:1c0d:936a:f685%eth0:60145] PHP Warning:  require_once(/var/www/html/h/hw-includes/config/config.php): Failed to open stream: No such file or directory in /var/www/html/h/hw-includes/site/load.php on line 15
[Fri Jul 07 22:25:36.113366 2023] [php:error] [pid 387153] [client fe80::2813:1c0d:936a:f685%eth0:60145] PHP Fatal error:  Uncaught Error: Failed opening required '/var/www/html/h/hw-includes/config/config.php' (include_path='.:/usr/share/php') in /var/www/html/h/hw-includes/site/load.php:15\nStack trace:\n#0 /var/www/html/h/header.php(11): require()\n#1 /var/www/html/h/index.php(13): require('...')\n#2 {main}\n  thrown in /var/www/html/h/hw-includes/site/load.php on line 15
[Fri Jul 07 22:26:13.335576 2023] [php:error] [pid 387162] [client fe80::2813:1c0d:936a:f685%eth0:60155] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'last_login' doesn't have a default value in /var/www/html/h/hw-includes/controllers/class-users.php:36\nStack trace:\n#0 /var/www/html/h/hw-includes/controllers/class-users.php(36): mysqli_query()\n#1 /var/www/html/h/hw-includes/controllers/class-users.php(26): signup->insert()\n#2 /var/www/html/h/hw-admin/account/login.php(101): signup->__construct()\n#3 {main}\n  thrown in /var/www/html/h/hw-includes/controllers/class-users.php on line 36, referer: https://pi.local/h/hw-admin/account/login.php
[Fri Jul 07 22:26:18.597716 2023] [php:error] [pid 387163] [client fe80::2813:1c0d:936a:f685%eth0:60171] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'last_login' doesn't have a default value in /var/www/html/h/hw-includes/controllers/class-users.php:36\nStack trace:\n#0 /var/www/html/h/hw-includes/controllers/class-users.php(36): mysqli_query()\n#1 /var/www/html/h/hw-includes/controllers/class-users.php(26): signup->insert()\n#2 /var/www/html/h/hw-admin/account/login.php(101): signup->__construct()\n#3 {main}\n  thrown in /var/www/html/h/hw-includes/controllers/class-users.php on line 36, referer: https://pi.local/

**Comment by hahuweb** [comment]
Hello darekmer I fixed the problem. Please reinstall this project. If you have the same problem, I will hide this project from the public and edit it again. Thank you for your time.

**Comment by darekmer** [comment]
Hi, the installer still cannot create an administrator account.:
8 05:26:21.641521 2023] [php:warn] [pid 389504] [client 192.168.0.66:64358] PHP Warning:  require_once(hw-includes/config/config.php): Failed to open stream: No such file or directory in /var/www/html/h/hw-includes/site/load.php on line 15
[Sat Jul 08 05:26:21.641836 2023] [php:error] [pid 389504] [client 192.168.0.66:64358] PHP Fatal error:  Uncaught Error: Failed opening required 'hw-includes/config/config.php' (include_path='.:/usr/share/php') in /var/www/html/h/hw-includes/site/load.php:15\nStack trace:\n#0 /var/www/html/h/header.php(11): require()\n#1 /var/www/html/h/index.php(13): require('...')\n#2 {main}\n  thrown in /var/www/html/h/hw-includes/site/load.php on line 15
[Sat Jul 08 05:26:54.290498 2023] [php:error] [pid 389503] [client 192.168.0.66:64368] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'user_img' doesn't have a default value in /var/www/html/h/hw-includes/controllers/class-users.php:36\nStack trace:\n#0 /var/www/html/h/hw-includes/controllers/class-users.php(36): mysqli_query()\n#1 /var/www/html/h/hw-includes/controllers/class-users.php(28): signup->insert()\n#2 /var/www/html/h/hw-admin/account/login.php(101): signup->__construct()\n#3 {main}\n  thrown in /var/www/html/h/hw-includes/controllers/class-users.php on line 36, referer: https://pi.local/h/hw-admin/account/login.php
[Sat Jul 08 05:27:10.579169 2023] [php:error] [pid 389510] [client 192.168.0.66:64370] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'user_img' doesn't have a default value in /var/www/html/h/hw-includes/controllers/class-users.php:36\nStack trace:\n#0 /var/www/html/h/hw-includes/controllers/class-users.php(36): mysqli_query()\n#1 /var/www/html/h/hw-includes/controllers/class-users.php(28): signup->insert()\n#2 /var/www/html/h/hw-admin/account/login.php(101): signup->__construct()\n#3 {main}\n  thrown in /var/www/html/h/hw-includes/controllers/class-users.php on line 36, referer: https://pi.local/h/hw-admin/account/login.php
[Sat Jul 08 05:28:06.418816 2023] [php:error] [pid 387950] [client 192.168.0.66:64386] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'user_img' doesn't have a default value in /var/www/html/h/hw-includes/controllers/class-users.php:36\nStack trace:\n#0 /var/www/html/h/hw-includes/controllers/class-users.php(36): mysqli_query()\n#1 /var/www/html/h/hw-includes/controllers/class-users.php(28): signup->insert()\n#2 /var/www/html/h/hw-admin/account/login.php(101): signup->__construct()\n#3 {main}\n  thrown in /var/www/html/h/hw-includes/controllers/class-users.php on line 36, referer: https://pi.local/h/hw-admin/account/login.php
[Sat Jul 08 05:28:38.871111 2023] [php:error] [pid 389503] [client 192.168.0.66:64392] PHP Fatal error:  Uncaught mysqli_sql_exception: Field 'user_img' doesn't have a default value in /var/www/html/h/hw-includes/controllers/class-users.php:36\nStack trace:\n#0 /var/www/html/h/hw-includes/controllers/class-users.php(36): mysqli_query()\n#1 /var/www/html/h/hw-includes/controllers/class-users.php(28): signup->insert()\n#2 /var/www/html/h/hw-admin/account/login.php(101): signup->__construct()\n#3 {main}\n  thrown in /var/www/html/h/hw-includes/controllers/class-users.php on line 36, referer: https://pi.local/

**Comment by darekmer** [comment]
Generally, the problem occurs with the public function insert() in the class-users.php file, specifically with 'user_img' and 'otp'. For example, I modified the code with the help of ChatGPT :) as follows:

```
public function insert()
{
    if (empty($this->error)) {
        $this->user_img = 'default_image.jpg'; 
        $this->otp = 'default_otp'; 
        $tsql = "INSERT INTO hw_users (username, email_phone, user_password, user_role, verification, last_login, user_location, user_device, user_status, login_at, reg_date, user_img, otp) VALUES ('$this->username', '$this->email_phone', '$this->password_hash', '$this->user_role', '$this->verification', '$this->last_login', '$this->user_location', '$this->user_device', '$this->user_status', '$this->login_at', '$this->reg_date', '$this->user_img', '$this->otp') ";
        mysqli_set_charset($this->conn, "utf8");
        $result = mysqli_query($this->conn, $tsql);
        if ($result == TRUE) {
            $this->select();
        }
    }
}
```

And in the database, I set the 'otp' column to varchar(200).

In the signup class, in the loginAt() function, I changed the date format to a format compatible with MySQL DATETIME. For example:

```
public function loginAt()
{
    $this->login_at = date("Y-m-d H:i:s");
    return $this->login_at;
}
```

Finally, after logging in, it still doesn't work, for example, creating a new page. The message "There a problem" is displayed. When adding a post, it hangs.
